server:
  port: 8801


spring:
  application:
    name: stream-consumer
  cloud:
    stream:
      binders:  # 在此处配置要绑定的 rabbitmq 的服务信息。
        defaultRabbit:  # 表示定义的名称，用于 binding 的整合
          type: rabbit  # 消息组件类型
          evironment:   # 设置rabbitmq 相关的环境信息
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest
      bindings: # 服务整合处理
        input: # 这个名字就是一个通道名称
          destination: studyExchange  # 表示要使用 Exchange 名称定义
          cnntext-type: application/json # 设置消息类型，本次为 JSON，文本则设置 "test/plan"
          binder: defaultRabbit # 设置要绑定的消息服务的具体位置
          #group: atcqvie-01

eureka:
  instance:
    # 访问路径可显示IP地址
    prefer-ip-address: true
    # Eureka 客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds: 1
    # Eureka 服务端在收到最后一次心跳后等待时间上限，单位为秒 (默认90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2
    instance-id: stream-consumer-8801
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
