server:
  port: 3344

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhengsh/ssm-laboratory-config.git
          search-paths:
            - springcloud-config
      label: master

eureka:
  instance:
    instance-id: config-${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/